docker-build:
  stage: build
  variables:
    NEXTJS_CHANGED: git diff-tree --no-commit-id --name-only -r HEAD | grep "frontend/"
    PROXY_CHANGED: git diff-tree --no-commit-id --name-only -r HEAD | grep "nginx/"
  before_script:
    - ls -lsa
    - docker info
    - docker-compose version
    - docker-compose ps
  script:
    - docker-compose config
    - |
      if [[ -z "$NEXTJS_CHANGED" ]]; then
        - docker-compose pull nextjs
        - docker-compose build nextjs
        - docker-compose up -d nextjs
      fi
    - |
      if [[ -z "$PROXY_CHANGED" ]]; then
        - docker-compose pull proxy
        - docker-compose build proxy
        - docker-compose up -d proxy
      fi
