image:
  name: docker/compose:latest

services:
  - docker:18.09-dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

stages:
  - build_and_deploy

build_and_deploy:
  stage: build_and_deploy
  script:
    - docker-compose down
    - docker-compose up --build
  only:
    - master
