image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yaml down
    - docker-compose -f docker-compose.yaml up --build
  only:
    - master
