services:
  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3000:3000/udp"
    networks:
      - next-start
  proxy:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
      DEBUG: 1
      RENEWAL_INTERVAL: "8d"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - next-start
    volumes:
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_secrets:/etc/letsencrypt

networks:
  next-start:
    driver: bridge

volumes:
  nginx_secrets:
