docker-build:
  stage: build
  before_script:
    - ls -lsa
    - docker info
    - docker-compose version
    - docker-compose ps
  script:
    - docker-compose config
    - |
      if [[ -z git diff-tree --no-commit-id --name-only -r HEAD | grep 'frontend/' ]]; then
        - docker-compose pull nextjs
        - docker-compose build nextjs
        - docker-compose up -d nextjs
      fi
    - |
      if [[ -z git diff-tree --no-commit-id --name-only -r HEAD | grep 'nginx/' ]]; then
        - docker-compose pull proxy
        - docker-compose build proxy
        - docker-compose up -d proxy
      fi
