image:
  name: docker:20.10
  entrypoint: ["/bin/sh", "-c"]

services:
  - name: docker:20.10-dind-rootless
#     alias: dind

# variables:
#   DOCKER_HOST: tcp://dind:2375

before_script:
  - apk add --no-cache docker-compose
  - docker-compose version
  - docker info
  - ls -lsa

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh ./bin/gitlab-deploy.sh
  only:
    - master
