docker-build:
  stage: build
  before_script:
    - ls -lsa
    - docker info
    - docker-compose version
    - docker-compose ps
  script:
    - docker-compose config
    - |
      if [ $(git diff-tree --no-commit-id --name-only -r HEAD | grep 'frontend/') ]; then
        docker-compose pull nextjs
        docker-compose build nextjs
        docker-compose down nextjs
        docker-compose up -d nextjs
      fi
    - |
      if [ $(git diff-tree --no-commit-id --name-only -r HEAD | grep 'nginx/') ]; then
        docker-compose pull proxy
        docker-compose build proxy
        docker-compose down proxy
        docker-compose up -d proxy
      fi
    - |
      if [ $(git diff-tree --no-commit-id --name-only -r HEAD | grep 'docker-compose.yml\|.gitlab-ci.yml') ]; then
        docker-compose pull
        docker-compose build
        docker-compose up -d
      fi
