image:
  name: docker/compose:latest
  entrypoint: ["/bin/sh", "-c"]

# services:
#   - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ls -lsa
    - ./bin/gitlab-deploy.sh
  only:
    - master
