image: docker:18.09.7-dind
services:
  - docker:18.09.7-dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apk add docker-compose
    - docker-compose -f docker-compose.yaml down
    - docker-compose -f docker-compose.yaml up --build
  only:
    - master
