image:
  name: docker:19.03
  entrypoint: ["/bin/sh", "-c"]

# services:
#   - name: docker:19.03-dind-rootless

before_script:
  - apk add --no-cache docker-compose
  - docker info
  - docker-compose version
  - ls -lsa

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh ./bin/gitlab-deploy.sh
  only:
    - master
