image:
  name: docker/compose:latest

services:
  - docker:19.03.12-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker info

stages:
  - build_and_deploy

build_and_deploy:
  stage: build_and_deploy
  script:
    - docker-compose down
    - docker-compose up --build
  only:
    - master
