image:
  name: docker:stable
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

before_script:
  - ls -lsa
  - apk add --no-cache docker-compose

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh ./bin/gitlab-deploy.sh
  only:
    - master
