image:
  name: docker:latest
  # name: docker/compose:latest

# services:
#   - docker:dind

stages:
  - build_and_deploy

build_and_deploy:
  stage: build_and_deploy
  script:
    - docker -v
    # - docker-compose down
    # - docker-compose up --build
  only:
    - master
