image: docker:latest
services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apk update && apk add docker-compose
    # - docker-compose -f docker-compose.yaml stop
    # - docker-compose -f docker-compose.yaml down --rmi all --volumes
    - docker-compose -f docker-compose.yaml down --rmi all --volumes
    - docker-compose -f docker-compose.yaml build --no-cache
    - docker-compose -f docker-compose.yaml up
    # - docker-compose -f docker-compose.yaml up -d
  only:
    - master
