image:
  name: docker/compose:latest

services:
  - name: docker:19.03.12-dind
    alias: dockerhost

variables:
   DOCKER_HOST: tcp://dockerhost:2375/
   DOCKER_DRIVER: overlay2
   DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

stages:
  - build_and_deploy

build_and_deploy:
  stage: build_and_deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker-compose down
    - docker-compose up --build
  only:
    - master
