image:
  name: docker:latest
  entrypoint: ["/bin/sh", "-c"]

# services:
#   - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - ls -lsa

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sh ./bin/gitlab-deploy.sh
  only:
    - master
