image: docker:19.03

before_script:
  - apk add --no-cache docker-compose
  - docker info
  - docker-compose version
  - ls -lsa

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker-compose -f ps
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker-compose pull
    - docker-compose up --build --force-recreate
  only:
    - master
