image:
  name: docker/compose:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker-compose -f down
    - docker-compose -f up --build
  only:
    - master
