image:
  name: docker/compose:latest
  entrypoint: ["/bin/sh", "-c"]

services:
  - name: docker:19.03.12-dind
    alias: dockerhost

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ls -lsa
    - sh ./bin/gitlab-deploy.sh
  only:
    - master
