deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind    
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client docker-compose
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose -f ./next-starter/docker-compose.yaml up -d --build"
  only:
    - master
