version: "3.8"

services:
  proxy:
    image: "nginx-proxy-cert"
    build:
      dockerfile: Dockerfile
      context: ./nginx
      cache_from: "nginx-proxy-cert"
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starter

  nextjs:
    image: "nextjs"
    build:
      dockerfile: Dockerfile
      context: ./frontend
      cache_from: "nextjs"
      shm_size: "1500m"
    shm_size: "1500m"
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "3000:3000"
    networks:
      - starter

networks:
  starter:
    driver: bridge
