version: "3.8"

services:
  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starter
    volumes:
      - type: volume
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: volume
        source: ./nginx/user.conf.d
        target: /etc/nginx/user.conf.d
      - type: volume
        source: ./nginx/certbot/extra_domains
        target: /etc/nginx/certbot/extra_domains

  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "3000:3000"
    networks:
      - starter

networks:
  starter:
    driver: bridge
