version: "3.8"

services:
  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3000:3000/udp"
    networks:
      - next-start
  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - next-start
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./certbot/extra_domains:/etc/nginx/certbot/extra_domains:ro
      - letsencrypt:/etc/letsencrypt

networks:
  next-start:
    driver: bridge

volumes:
  letsencrypt:
