version: "3.8"

services:
  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starter
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/conf.d:/etc/nginx/user.conf.d
      - ./certbot_extra_domains:/etc/nginx/certbot/extra_domains

  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "3000:3000"
    networks:
      - starter

networks:
  starter:
    driver: bridge
