version: "3.8"

services:
  proxy:
    image: staticfloat/nginx-certbot
    # restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starter
    volumes:
      - ./nginx/user.conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    # restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "3000:3000"
    networks:
      - starter

networks:
  starter:
    driver: bridge

volumes:
  letsencrypt:
