version: "3"

networks:
  starter:
    driver: bridge

volumes:
  nginx_secrets:

services:
  proxy:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starter
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./certbot_extra_domains:/etc/nginx/certbot/extra_domains:ro
      - nginx_secrets:/etc/letsencrypt

  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - 3000:3000
    networks:
      - starter
