version: "3.8"

services:
  proxy:
    image: "proxy"
    build:
      dockerfile: Dockerfile
      context: ./nginx
      cache_from: 
      - "proxy"
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starter

  nextjs:
    image: "nextjs"
    build:
      dockerfile: Dockerfile
      context: ./frontend
      cache_from: 
      - "nextjs"
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - starter

networks:
  starter:
    driver: bridge
